server:
  port: 8092
axon:
  axonserver:
    servers: localhost
    enabled: true
spring:
  application:
    name: shipment-query-service
  datasource:
    url: jdbc:h2:mem:shipment_test;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
  h2:
    console:
      enabled: true
  jpa:
    hibernate:
      ddl-auto: create
