spring:
  application:
    name: gateway-service
  cloud:
    gateway:
      discovery:
        locator:
          lower-case-service-id: true
    discovery:
      enabled: true
#    config:
#      enabled: false
eureka:
  instance:
    prefer-ip-address: true
server:
  port: 8888