spring:
  application:
    name: tracking-query-service
  profiles:
    active: test
  cloud:
    config:
      enabled: false
      discovery:
        enabled: false
  config:
    import: optional:configserver:${CONFIG_SERVICE_URL:http://localhost:9999}
server:
  port: 8094
management:
  endpoints:
    web:
      exposure:
        include: "*"
