spring:
  application:
    name: tracking-query-service
  cloud:
    discovery:
      enabled: true
  datasource:
    url: jdbc:h2:mem:tracking_db
  h2:
    console:
      enabled: true
  jpa:
    hibernate:
      ddl-auto: create
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8080/realms/cqrs-event-sourcing
      authorizationserver:
        endpoint:
          jwk-set-uri: http://localhost:8080/realms/cqrs-event-sourcing/protocol/openid-connect/certs
server:
  port: 8094
eureka:
  instance:
    prefer-ip-address: true
axon:
  axonserver:
    servers: localhost
    enabled: true
  serializer:
    general: jackson

