spring:
  application:
    name: shipment-command-service
  cloud:
    discovery:
      enabled: true
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8080/realms/cqrs-event-sourcing
      authorizationserver:
        endpoint:
          jwk-set-uri: http://localhost:8080/realms/cqrs-event-sourcing/protocol/openid-connect/certs

server:
  port: 8091
eureka:
  instance:
    prefer-ip-address: true
axon:
  axonserver:
    servers: localhost
    enabled: true
  serializer:
      general: jackson
      messages: jackson
      events: jackson

