spring:
  application:
    name: config-service
  cloud:
    discovery:
      enabled: true
    config:
      server:
        git:
          uri: https://github.com/AbdelilahSaouiri/config-repo-cqrs-evs
          username: AbdelilahSaouiri
          password: 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
          default-label: config
server:
  port: 9999
management:
  endpoints:
    web:
      exposure:
        include: "*"
eureka:
  instance:
    prefer-ip-address: true
  client:
    service-url:
      defaultZone: ${DISCOVERY_SERVICE_URL:http://localhost:8761/eureka}