spring:
  application:
    name: config-service
  cloud:
    discovery:
      enabled: true
    config:
      server:
        git:
          uri: ${GIT_URI}
          username: ${GIT_USER}
          password: ${GIT_PASSWORD}
          default-label: ${GIT_LABEL}
          clone-on-start: true
  profiles:
    active: dev
server:
  port: 9999
management:
  endpoints:
    web:
      exposure:
        include: "*"
eureka:
  instance:
    prefer-ip-address: true
  client:
    service-url:
      defaultZone: ${DISCOVERY_SERVICE_URL:http://localhost:8761/eureka}